### ISSUE TITLE
Sidebar display problem in "Narrow" mode when the window is wide

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#27]
You probably have noticed it (you said yesterday that you are working on the css of the script) but to make sure:

screenshot :
![vlctube - cause sidebar cut 2](https://cloud.githubusercontent.com/assets/3327540/4689782/67310ea6-56cb-11e4-84cd-5c8f66f15324.PNG)

=====
STR
=====
create a new profile
install GM
install VLCtube
Make the window narrower than about 1300px.
Open https://www.youtube.com/watch?v=ZO-BxMXvdCU
Make the window wider than about 1300px.
Reload the page
If its still OK try Reload again
Now look at the top of the related videos sidebar - it is cut.

================
workaround to fix:
================
Make the window narrower than about 1300px.
Reload the page

-------------------
And a request :
-------------------
While fixing the css please make it compatible with the top video bar of "view-youtube-videos-by-same-user" script.
https://greasyfork.org/scripts/946-view-youtube-videos-by-same-user

TIA.

My monitor 1920x1200
VLCtube 57.26
GM 2.2
Win 7 x64

**Comment by jackun** [comment]
Until next time ;-P
