### ISSUE TITLE
(solved) a small suggestion - exclude YT's search results page

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#33]
exclude - http*://www.youtube.com/results*
I know I can add it manually through the userscripts > VLCtube > Options but it would be better if it's added "built in" to the script's code.

**Comment by LL25255252** [comment]
First, sorry for returning to this thread after more than 3 months...and thanks for giving me the "steps to reproduce" so I can understand this SPF thing. I followed this STR and now I understand why VLCtube should not be excluded from YT's search results page.
Many thank also for uploading here your SPF fix for "View Youtube videos by same user" script. After I installed it SPF started to work again (I'm seeing the read bar).

Did you make your fix/changes onto the script's v1.4.4 2014-07-13 or onto  v1.4.3 2014-05-14 ?
Is it OK with you that I suggest your version to the original dev of the script ?
https://greasyfork.org/en/scripts/946-view-youtube-videos-by-same-user

**Comment by jackun** [comment]
Well, he's more than welcome to take a look ;) I think it mostly works.

**Comment by LL25255252** [comment]
Did you make your fix/changes onto the script's v1.4.4 2014-07-13 or onto v1.4.3 2014-05-14 ?

**Comment by jackun** [comment]
Looks like v1.4.4

**Comment by LL25255252** [comment]
I've just posted about your "View Youtube videos by same user"  without disabling SPF version on the the script's page at greasyfork.org
https://greasyfork.org/en/forum/discussion/3203/suggestion-a-link-to-a-version-which-doesn-t-disable-spf

I think that you can finally close this thread/issue and thanks again.
