### ISSUE TITLE
Settings are not saved or read in ff 35beta 

### ISSUE THREAD

**Issue by altunyurt** [jackun/VLCTube#37]
I've recently upgraded ff to v35beta, and vlctube started to use default settings. Custom settings are not saved and it's always loaded with the default settings.

v58.0 on ff35beta

**Comment by Sonic0170** [comment]
firefox stable moved to v35 now, so im going through this issue now also

**Comment by jackun** [comment]
Array from GM_listValues cannot be accessed from GM. Array indexing just gives 'undefined' values. Weird.

**Comment by Sonic0170** [comment]
so a greasemonkey bug that hasnt been fixed yet it sounds like

**Comment by Sonic0170** [comment]
a curious comment at end of this issue seems relevant
https://github.com/greasemonkey/greasemonkey/issues/2004

**Comment by jackun** [comment]
Hah, cloneInto()-ing the values into sandbox works. (Until next time.....)

**Comment by Sonic0170** [comment]
one final question, is there a reason the video's height is locked, is it possible to have a "player Height" option for custom player sizes?

**Comment by jackun** [comment]
I haven't bothered/had time to deal with it yet. But I'll see tonight/tomorrow.

**Comment by Sonic0170** [comment]
ok thank you

**Comment by jackun** [comment]
Sonic0170, try [this WIP version](https://dl.dropboxusercontent.com/u/235773/25318.user.js). It is quirky as hell. I don't remember what was needed for the player div to fall back to the left side properly when unwidening.

**Comment by Sonic0170** [comment]
thats amazing, way to go jackun, this is exactly what i was looking for, a matter of fact, i think i like it centered over aligned left, this is just perfect thank you so much

**Comment by Sonic0170** [comment]
when or if you merge these changes into master ima delete the fork and remove the link on the greasyfork page

**Comment by Sonic0170** [comment]
ok so something seems to be happening, it loads the settings of the version before i installed your WIP version, when i change the settings it holds for a little while and then after i jump around the web for a minute or 2 and then watch another video, it drops back to the settings i had from the older version.

this sounds strange but i have no idea whats happening, the previous settings are ok and all but its a strange behavior.

i did try reloading to save settings but it still repeats the same behavior, i would assume if i deleted all the old settings by removing all vlctube files from my profile would cause the settings to reset to default if i did the same thing, ill keep testing and see if it keeps happening, but i wanted to let you know for now

**Comment by jackun** [comment]
Saving might be busted. Reinstall from dropbox and try then.

**Comment by Sonic0170** [comment]
ok so i tried deleting all vlctube stuff from my profile and even tried a fresh temporary profile and the script loads but the whole player is missing, im gonna load your current master script, set the setting their and then load your wip and see if it works like before again

**Comment by Sonic0170** [comment]
ok so i tried that and now the player is just missing like i previously said, this is weird, im not sure how it was working for me from before

**Comment by jackun** [comment]
Maybe firefox is blocking the plugin? Set it to always activate.

**Comment by Sonic0170** [comment]
its already set to always active, something just refuses to work now, did you change anything from the wip version you posted when i installed it the first time?
im curious because you used strikeout on your paragraph saying you missed something so im wondering if you altered the wip

**Comment by jackun** [comment]
ctrl+shift+j and see what's up

**Comment by Sonic0170** [comment]
"Custom size:" 1280 720 undefined "97%" watch:2306
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead comments:264
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead comments:1393
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead comments:676
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead comments:1084
Use of getAttributeNode() is deprecated. Use getAttribute() instead. comments:79
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead comments:119
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead comments:55
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead

**Comment by Sonic0170** [comment]
there is a bunch of other error i dont understand if i enable css logging

**Comment by jackun** [comment]
Something idiotic is happening. Logging GM_getValue:

    Line 3211: GM_getValue is function() ....blah...

Actually calling it:

    Line 3212: GM_getValue is undefined

**Comment by Sonic0170** [comment]
all this new security is such a hassle lol

**Comment by jackun** [comment]
It seems to be injecting script code twice into document, ehh.

**Comment by Sonic0170** [comment]
odd, so how is the current master working while your minor changes in this wip arent?
i would assume you didnt have to do much

**Comment by jackun** [comment]
"undefined" value type was giving some trouble. Try now.

**Comment by Sonic0170** [comment]
same link in previous comment?

**Comment by jackun** [comment]
yep, ok, nighty-night for today from here, hehe.

**Comment by Sonic0170** [comment]
gnight and thank you

**Comment by Sonic0170** [comment]
ok so the width percentage defaults to 86% and won't let me change it in the options window, otherwise all other options save properly.
so i went into the script and changed the default to 97% and it worked so i think something is preventing the custom option from loading over the default.

ill just leave this here for you when you wake up and have time

**Comment by jackun** [comment]
Right, should have a check for undefined values when saving too.

**Comment by Sonic0170** [comment]
that worked thank you
