### ISSUE TITLE
Request - center the subtitles

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#42]
The subs (closed captions) are now aligned to the left. Can you please center them ?

A video foe example:
https://www.youtube.com/watch?v=yNe_HdayTtY
TIA

**Comment by Sonic0170** [comment]
i can confirm that on that particular video

**Comment by LL25255252** [comment]
Here's another one (aligned to the left):
https://www.youtube.com/watch?v=y6Sxv-sUYtM

**Comment by jackun** [comment]
Last time I messed with subtitles I couldn't get it to respect the alignment parameter so only safe option was to align it to left and hope the text fits on display.

**Comment by Sonic0170** [comment]
it does fit properly

**Comment by jackun** [comment]
v60 works for me now :P

**Comment by LL25255252** [comment]
First, many thanks for adding the center/align menu.

Sorry that I only tested on one video but I had a Firefox freeze
https://www.youtube.com/watch?v=yNe_HdayTtY
It happened somewhere between 1:00 and 2:30 after playing the video from 0:00.

Tested on a new fresh firefox 37 profle.
installed V60 and enabled the English subs.
Win 7 x64
