### ISSUE TITLE
Some URLs with embedded parameters not recognized

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#43]
Some videos are prevented from playing outside youtube.com.
I got a link to such a video in an email I received.
I clicked on the mail attachment youtube thumb and gmail opened the theater preview mode with a "watch this video on youtube (only)" hyperlink message . I cliked the link and got this error from VLCtube "VLCTube: Unable to find video source"

[the url with the embedded param](https://www.youtube.com/watch?v=qZx3akGNilo&feature=player_embedded)

TIA

**Comment by jackun** [comment]
It seems to put a <script/> element into the "player-api" div with the "feature" parameter and ofcourse the script overwrites it there, ugh.

**Comment by jackun** [comment]
Script loaded the player before variables where ready for whatever reason. Now it delays it a bit so see if other stuff still works too ;)

**Comment by LL25255252** [comment]
Many thanks for the quick fix.
