### ISSUE TITLE
Changes in v59 caused VLCTube to stop working in Firefox 36 beta 10

### ISSUE THREAD

**Issue by asampal** [jackun/VLCTube#44]
I'm using Windows 8.1 64 bit, Firefox 36 beta 10

Everything was fine using the previous version, but with v59 that was just pulled down, I can no longer see videos on YouTube. The console shows two lines of relevant output:
"no source"
"VLCTube: Unable to find video source"

**Comment by jackun** [comment]
Oops. Ok, try now v59.1

**Comment by asampal** [comment]
That fixed it - thanks! 
What's wrong with 38 beta? Is it the process per tab stuff?

**Comment by jackun** [comment]
Just a quick try, but looked like it failed to access the plugin's interfaces.
