### ISSUE TITLE
Embedded YouTube video doesn't play on wimp.com

### ISSUE THREAD

**Issue by asampal** [jackun/VLCTube#45]
Using Windows 8.1 64 bit, Firefox 36 beta 10, VLCTube v59.1

Videos on wimp.com have audio, but video does not work when VLCTube is enabled.

For example, see [this](http://www.wimp.com/reactiondigital).

**Comment by Sonic0170** [comment]
to clarify "youtube video's embedded on wimp.com"
i can verify that adio plays but video is either missing or a frozen image

**Comment by jackun** [comment]
They use JW  html5 player. Best way probably is to just exclude wimp.com.

**Comment by asampal** [comment]
Sounds reasonable and v59.5 does that, so closing.
