### ISSUE TITLE
Request - Add 2x (or other preset rate) speed button

### ISSUE THREAD

**Issue by asampal** [jackun/VLCTube#47]
I pretty much always watch informational videos at 2x speed and other videos at normal speed. It would be nice to have a button (just like the one for 1x) to go to this speed rather than having to adjust the speed bar. Since the faster-than-1x-speed would probably vary from person to person, it would make sense for the speed that is set by this button to be configurable.
In addition, if this preset speed button is added, another configuration setting could allow for the removal of the speed bar when this preset is enabled.

**Comment by Sonic0170** [comment]
it seems you found the feature, this issue should be closed as it is no longer valid

**Comment by asampal** [comment]
How have I found the feature? This issue is not about a speed slider, but rather about adding a button to switch to a specific playback speed value - just as there is one to go  back to 1x.

**Comment by Sonic0170** [comment]
oh i assumed you were just talking about speed control by itself, so your talking about a button, sorry seems i didn't understand correctly

**Comment by asampal** [comment]
Added PR #50
