### ISSUE TITLE
Buffer length

### ISSUE THREAD

**Issue by Pszek** [jackun/VLCTube#48]
I can't set a higher bufferenght (60). The number resets every time.

**Comment by jackun** [comment]
Yes. VLC web plugins docs say 60 secs is maximum.

**Comment by Pszek** [comment]
I am sorry, I didn't notice anything incorrect or misguiding in my sentence earlier. By writing 60 in brackets, I meant I couldn't set this exact value. I tried with different values as well. I even tried setting it manually (I changed value in all 2 or 3 places in plugin file), but actually it showed only the changed value yet it was still 5 in buferring. I would like to thank You for this plugin, I've been using it for months. Somehow flash plugin has issues and generates issues when it's "present" in few windows (I have usually open ca. 60). Your piece of work saved my nerves on numerous occasions.

**Comment by jackun** [comment]
Ok, I missed that option. Should work now.

**Comment by Pszek** [comment]
It worked like a charm. Thank You for blitz response and solution.

**Comment by LL25255252** [comment]
Jackun, can you please explain what this "Buffer length" parameter is for ?
I never changed it. It is set on 5 seconds and works fine.
Thanks in advance.

**Comment by Sonic0170** [comment]
its the amount in seconds how much of the video is loaded/buffered before it starts playing

**Comment by LL25255252** [comment]
@Sonic0170, thank you.
