### ISSUE TITLE
Compact volume button is shorter than the other buttons

### ISSUE THREAD

**Issue by asampal** [jackun/VLCTube#51]
When using the compact volume option, the resulting button inserted among the others is too short.

**Comment by asampal** [comment]
Added PR #52

**Comment by jackun** [comment]
Does this work for you? https://github.com/jackun/VLCTube/blob/93c74700dfd0e09df26acfb828cc4aed81425a5f/25318.user.js
Seems too hacky though. Adds a div next to volume button and then moves it left.

**Comment by asampal** [comment]
The height looks right now, but I have a couple of comments on the other parts of the compact volume control.

1. While the video is first playing, the vertical slider's corners aren't rounded. They only become round when the video finishes playing. Also, the knob seems to not be centered on the slider.
2. I think the text showing the percent value of the slider isn't needed. Moving the knob feels relatively laggy, probably due to the text being refreshed while dragging is happening. My vote would be to not show a textual value.
