### ISSUE TITLE
Request - make it compatible with "YouTube Video and Audio Downloader" addon

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#57]
https://addons.mozilla.org/en-us/firefox/addon/youtube-video-and-audio-dow/
I'm using this addon to download the audio part of the video. It gives direct links to the m4a (AAC) audio parts.
If VLCtube is enabled then it blocks the addon's "download links" panel.

TIA.

**Comment by jackun** [comment]
I don't know, it assume it's a flashplayer and injects its menu right after VLC plugin. But when using thumbnails, VLC is hidden so no menu. Seems to kind of work, though.

**Comment by michaelmotes** [comment]
This still works with VLCTube, doesn't offer automatic conversion to audio though. 
https://addons.mozilla.org/En-us/firefox/addon/download-youtube/

But, you can use VLC to convert mp4 to audio pretty easily:
http://stackoverflow.com/questions/17607061/vlc-command-line-batch-file-to-rip-audio-cd/17607084#17607084

**Comment by LL25255252** [comment]
@michaelmotes thanks for your suggestion. Here's mine: Creating mp3 from mp4 can be performed with the new https://cloudconvert.com/
You can set there the start-time and end-time before converting.
