### ISSUE TITLE
Lower part

### ISSUE THREAD

**Issue by Pszek** [jackun/VLCTube#60]
Dear Jackun,,

Lower part of the player (with controls) is not accessible (it looks like it's extended beyond the player screen)..

With Regards,
Pszek

**Comment by Sonic0170** [comment]
yes it seems the are listed as <div id="watch7-main" class="clearfix"> which seems to be sitting on top of the vlctube buttons, did google change the CSS again?

**Comment by Pszek** [comment]
hmm, acutally(maybe after Your update) problem still persists, but the different one - video is autoplayed in the "background" and the controls do nothing

**Comment by jackun** [comment]
Yeah, had something similar, but reopening firefox worked (or purge cache maybe). Seems that some of the page was cached as it gives an error that it got no "#placeholder-player" div.

**Comment by Pszek** [comment]
Interestin thing, that switching quality "forks" video - the player starts and behaves normally, unfortunately first instance ("the background" video) still plays. Maybe this will somehow help You (don't know web programming yet, and dunno if ever)

**Comment by jackun** [comment]
Made the resizer wait for the #placeholder-player. I'll see later what's really going on.

**Comment by Sonic0170** [comment]
sorry im late,
so yeah this happened to me on 61.1, i didn't realize it was fixed on 61.2, so after your fixes up to 61.2, the buttons were no longer covered and everything was working.
so yeah i forgot to update, sorry @jackun

**Comment by Pszek** [comment]
now it looks like everything is working. thanks
