### ISSUE TITLE
is it just me? (large empty space on right side of page)

### ISSUE THREAD

**Issue by Sonic0170** [jackun/VLCTube#61]
from top to bottom, at least for me so far there is a empty space on the right side of the screen triggering the horizontal scroll bar.
is it just me, is this a known issue, or is this an issue with youtube itself?

**Comment by jackun** [comment]
Ok, wider custom width is messing something up.

**Comment by Sonic0170** [comment]
so far i don't see anything resembling a black triangle jumping or floating about, but that strange empty space has now vanished thank you very much ^.^

**Comment by Sonic0170** [comment]
ill close this for now and update you if anything weird happens, and if so ill reopen it

**Comment by Sonic0170** [comment]
also i suggest a version bump since greasyfork won't push a update without a version bump
