### ISSUE TITLE
61.9+ fails to remove youtube's own  player 

### ISSUE THREAD

**Issue by altunyurt** [jackun/VLCTube#67]
61.8 works perfectly fine, but newer versions fail to load vlc player. vlc player first shows up, and suddenly youtube's own player takes over. 

ff versions are 38 and 39. 

firebug console displays these lines

"Hijacked createElement:" "video" 25318.user.js:4689:3
"video seems to be unavailable" watch:3878:4

**Comment by jackun** [comment]
Even with v61.11? Anyway, report any more finds in issue #66
