### ISSUE TITLE
(solved) Not working on a clean Firefox profile

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#68]
It DOES work on my main profile but not in a new/fresh profile.

STR:
- create a new profile
- install GM 3.2
- install VLCtube 61.11
- open a yt pgae. (I tried it on 5 different videos - not only on VEVO videos and not only on playlists)

result - no player, just a a black rectangle. 

GM 3.2
VLC Web Plugin 2.2.1.0
Firefox 38.0.5
Win 7 x64
TIA.

**Comment by jackun** [comment]
GM_getValue checked for `undefined` and fresh profile should have these unset settings/values set to `undefined` afaik, but somewhere it got set to `null` and GM_getValue didn't return default value.

**Comment by LL25255252** [comment]
Yes, the new  VLCtube 61.12 fixed. Many thanks !! 
...and you can close this issue.
