### ISSUE TITLE
(Solved) Fail to play VEVO vids on 2 cases

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#69]
If the first video played after Firefox is launched is from VEVO then VLCtube fails.

STR:
create a new profile
install GM 3.2
install VLCtube 61.12 (the new version)

Problem 1:
- Open a VEVO video like https://www.youtube.com/watch?v=hRK7PVJFbS8
- result - you get the "e" icon ( VLCtube fail to play)

Problem 2 (after reload)  (update June 25th):
- When you are on a VEVO page (regular youtube's watch page)
- e.g. https://www.youtube.com/watch?v=liZm1im2erU
- Reload the page
- try to play the video 
- I ALWAYS get an "e"

Choosing VEVO from the related videos - no problem.

GM 3.2
VLC Web Plugin 2.2.1.0
Firefox 38.0.5
Win 7 x64
TIA.

**Comment by jackun** [comment]
Can you post console log ( CTRL+J) as I can't seem to repro this.

**Comment by LL25255252** [comment]
http://www.mediafire.com/download/rjf98vci7to6se5/VLCtube_vevo_issue.rar

**Comment by LL25255252** [comment]
I constantly still have this problem. Any news ? 
@jackun , Have I understand you correctly and my STR reproduce no problems to you ? What are your specs (version of VLC and Firefox).
@Sonic0170, have you also tried my STR ?
TIA.

**Comment by LL25255252** [comment]
OK...I found a workaround...tried several times and it seems to work on those problematic 720p Vevo vids:
So when you get the "e" on Vevo videos:
1. change the format from 720p to 360p (on the drop-down format menu) and then back to 720p
2. start the video (click the "s")

**Comment by Sonic0170** [comment]
well @LL25255252 im not 100% what STR stands for, but with that video link in your first post, I have no issues playing it whatsoever.
have you tried a newer or nightly version of VLC to see if it helps?

**Comment by LL25255252** [comment]
Thanks Sonic for taking the time to help.
Tried  VLC nightly 3.0.0 64bt - but no change.
Sonic, have you tried my STR (Steps To Reproduce) on a new profile? You probably have different settings for VLCtube than mine so if you test in a new profile with the VLCtube defaults then we'll both  have the same settings.

I'm changing the title of the issue b/c it now happens not only after browser launch but on every VEVO video. It happens only if the "FIRST" video of a tab is a VEVO one. No problems after clicking on a related video thumb even if it is a VEVO one.
After using my workaround (changing the video format - see my post above) VEVO vids play OK but if i Reload the page it happens again so I need to use my workaround again.

**Comment by Sonic0170** [comment]
no changes, try switching to 32bit vlc since the official release of firefox comes only in 32bit builds for the time being, its possible a 64bit version might have unforeseen bugs.
not sure if the web plugin is 64bit also but its a thought.

in the end this might just be an isolated incident, ive had those happen to me and jackun could never figure out why they happened to me, but i cant say how they were fixed because i just ended up getting lucky and they vanish.

**Comment by LL25255252** [comment]
@Sonic0170 , thanks again for the help.
Switched to 32bit vlc latest build but to avail (same problem).
BTW - after I installed it the web plugin version changed from 2.2.1.0 to 2.2.2.0
All my tests are done in a new/fresh firefox profile.

You said at the beginning "no changes" - what do you mean ? Still, I can't understand. Have you tried my STR on a new profile ?

**Comment by Sonic0170** [comment]
i can create a new temp profile for testing using the profile manager, but even with a new profile i still had no issues.
honestly i dont use the term STR, but yes i would have to install all the items to be able to test it.

**Comment by LL25255252** [comment]
"... but yes i would have to install all the items to be able to test it.". *"all the items"* - SORRY (really) for the nagging...but aren't *ALL the items* just Greasemonkey and VLCtube. That's it. Nothing more to install. As I mentioned in the STR I want you to use VLCtube default settings.
BTW - the VLC web plugin is automatically installed by the profile manager (no need to install it).

**Comment by Sonic0170** [comment]
@LL25255252 im sorry your having such issues but you know what i meant when i said that and yes all the setting would be at default, i really wish i could reproduce your issue but im at a loss

**Comment by LL25255252** [comment]
There's another case when it fails to play VEVO video - see my opening post. Therefore I updated the issue title.
@Sonic, thanks again for taking the time to help.

**Comment by jackun** [comment]
Might be a timing issue. [Try this](https://dl.dropboxusercontent.com/u/235773/25318.user.js). It should re-add the url with proper signature when the decipherer parsing is done.

**Comment by LL25255252** [comment]
:+1: Great news.
Many Thanks @jackun  for the new 61.15.  All is working now, including VEVO. It also fixed issue #70 
On the last few days it was not just VEVO vids. I had the "e' in regular vids...Now EVERYHING is fixed. :) 

BTW - I have installed 61.15 from the homepage - https://github.com/jackun/VLCTube/blob/master/25318.user.js . Is it the same as https://dl.dropboxusercontent.com/u/235773/25318.user.js ?

**Comment by jackun** [comment]
Github one is now newer, re-fixed the GM_getValue, should work with new clean profiles again >_>

**Comment by LL25255252** [comment]
Installed and tested the new 61.6 and everything is OK.
