### ISSUE TITLE
(Solved) problem with configuration window

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#70]
STR (steps to reproduce) :
create a new profile
install GM
Open a youtube's page. e.g. https://www.youtube.com/watch?v=w88p3xq5KsI
Open VLCtube's configuration window
Untick the "autoplay" and the "autoplay playlist" checkboxes.
Close VLCtube's configuration window
Reload

Result:
These checkboxes.are still ticked.

VLCtube 61.14
GM 3.2
VLC Web Plugin 2.2.2.0
Firefox 38.0.5
Win 7 x64
TIA.

**Comment by LL25255252** [comment]
Here's the Error Console log:

This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] crossdomain.xml
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] generate_204
"Hijacked createElement:" "video" 25318.user.js:4690:2
uncaught exception: j$@https://s.ytimg.com/yts/jsbin/html5player-en_US-vflPcWTEd/html5player.js:1701:471
g$@https://s.ytimg.com/yts/jsbin/html5player-en_US-vflPcWTEd/html5player.js:1697:448
g$.create@https://s.ytimg.com/yts/jsbin/html5player-en_US-vflPcWTEd/html5player.js:1699:111
ytplayer.load@https://www.youtube.com/watch?v=w88p3xq5KsI:199:25839
@https://www.youtube.com/watch?v=w88p3xq5KsI:199:26000
@https://www.youtube.com/watch?v=w88p3xq5KsI:199:25936
 <unknown>
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] watch:1079:0
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] videoplayback
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] videoplayback
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] jsapi
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] content.I.js
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create frameworks-808fcfcd63c9ecba3e84453f540cb1cbafde48c6b30c1d51ebd4e67e88ff66bd.js:34:1559
"Hijacked createElement:" "video" 25318.user.js:4690:2
uncaught exception: j$@https://s.ytimg.com/yts/jsbin/html5player-en_US-vflPcWTEd/html5player.js:1701:471
g$@https://s.ytimg.com/yts/jsbin/html5player-en_US-vflPcWTEd/html5player.js:1697:448
g$.create@https://s.ytimg.com/yts/jsbin/html5player-en_US-vflPcWTEd/html5player.js:1699:111
ytplayer.load@https://www.youtube.com/watch?v=w88p3xq5KsI:178:25818
@https://www.youtube.com/watch?v=w88p3xq5KsI:178:25979
@https://www.youtube.com/watch?v=w88p3xq5KsI:178:25915
 <unknown>
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] videoplayback
This site makes use of a SHA-1 Certificate; it's recommended you use certificates with signature algorithms that use hash functions stronger than SHA-1.[Learn More] videoplayback

**Comment by jackun** [comment]
I don't know why I thought the previous GM_getValue patch would work, uh.
