### ISSUE TITLE
Related videos are wrongly marked as in the "watched later" list

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#75]
STR (Steps to reproduce):
1. Enter the watch page of video A.
2. Click the "clock" button. (as a result video A is correctly added to the Watch List).
3. Click on video B from one of the related videos on the right sidebar.
4. Video B watch page is loaded with a "tick" sign near the "clock" button although it is not on the Watch List.

TIA.

Pale Moon 25.7
win 7(x64)
GM 1.15.1
VLCtube 61.18

**Comment by LL25255252** [comment]
Yes, the new 61.20 version fixed this issue. 

Still if you want it to be perfect then another small thing. 
1.  Enter the watch page of a video.
2. Click the "clock" button. (as a result the clock gets a "tick" sign near it).
3. Now when the cursor hovers the clock button the "tick" sign suddenly disappears (though no functionality problems).

**Comment by jackun** [comment]
It's visual error caused by how CSS styling is set-up currently. `:hover` effect for making the buttons background lighter overrides the style with the 'tick' as background image, uh.
