### ISSUE TITLE
Request - add compatibility with GM for Seamonkey & Palemoon

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#77]
Request - add compatibility with GM fork for Seamonkey & Palemoon

The latest GM (ver. 3.4.1) has been recently forked to GM 3.4.1 version for SeaMonkey & PaleMoon.
https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.4.1Fork

The latest VLCtube crashes on every video (doesn't even load VLCtube bars and buttons).

var msg = JSON.parse (event.data);

[05:22:04.637] SyntaxError: JSON.parse: unexpected end of data @ file:///C:/Users/USER/AppData/Roaming/Moonchild%20Productions/Pale%20Moon/Profiles/dm5nlis3.vlctube/gm_scripts/VLCTube/25318.user.js:4661

Tested on a new fresh profile
VLCtube 61.18
VLC web plugin 2.2.2.0
GM 3.4.1 version for SeaMonkey & PaleMoon.
palemoon 25.7.0
Won 7 x64

BTW (1) - if I install the very old GM 1.15 then it works fine in PaleMoon.

BTW (2) - It's still working on my firefox (ver 41.0)

**Comment by LL25255252** [comment]
Not working also in PaleMoon with Scriptish.

Here's a Scriptish version compatible with PaleMoon :
http://www.mediafire.com/download/trzqp2jr28f1wcc/scriptish_OKwith_palemoon%40erikvold.com.xpi
[I've taken the latest Scriptish version and updaed the install.rdf and chrome.manifest and now it's compatible with the PaleMoon browser.]

From the error console:

[06:11:42.422] [VLCTube@0d92f6be108e4fbee9a6a0ee4366b72e] 
TypeError: head is undefined @ file:///C:/Users/USER/AppData/Roaming/Moonchild%20Productions/Pale%20Moon/Profiles/n8um6emy.GM%20latest%20-%20fix/scriptish_scripts/vlctube@0d92f6be108e4fbee9a6a0ee4366b72e/vlctube@0d92f6be108e4fbee9a6a0ee4366b72e.user.js:4521

The error is in function injectScript(src) --> 	head.appendChild(script);

VLCtube 61.20
Scriptish_OKwith_palemoon  0.1.11.1
PaleMoon 25.7.2
Win 7 x64

**Comment by LL25255252** [comment]
Great work !! many thanks !! The new 62.20 is now compatible with Scriptish in PaleMoon.

Now finally I can run VLCtube on PaleMoon :)

Hve you looked into my first post here ? Is there a chance you'll make it compatible also with the new "GM 3.4.1 version for SeaMonkey & PaleMoon" ?
https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.4.1Fork

**Comment by jackun** [comment]
Works for me with Seamonkey 2.38 on Arch and greasemonkey-3.4.1-fx_forkBranch_SeaMonkey_PaleMoon.xpi

**Comment by LL25255252** [comment]
Great !! With the new 61.23 version VLCtube can now also work with the new "GM 3.4.1 version for SeaMonkey & PaleMoon" https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.4.1Fork

Again, many thanks :+1:
