### ISSUE TITLE
for me enabling the mute button causes VLCTube to stop working all together

### ISSUE THREAD

**Issue by Sonic0170** [jackun/VLCTube#83]
this started happening with the recent vlctube update 61.29 and im using the normal release of firefox which is at 45.0.1 on windows now.
i tested it by removing and cleaning out any trace of vlctube and installing fresh in which it started working fine, but when i enable the mute button feature it just stops working and the area where a player would be is blank.
im going to test one more time by enabling everything except the mute button to see if thats the only cause, brb.

**Comment by Sonic0170** [comment]
ok i have confirmed this odd bug.
it only happens when i enable "show mute button".
its possible its only me but i cant say for sure and i dont get why the mute option would make the whole player fail.

**Comment by jackun** [comment]
Crap. Deleted a bit too much stuff when fixing lint errors.

**Comment by Sonic0170** [comment]
lol i see well im glad im not just being dumb somehow

**Comment by Sonic0170** [comment]
ok it works now thank you jackun
