### ISSUE TITLE
HTML5 player keeps blasting in the background

### ISSUE THREAD

**Issue by Sonic0170** [jackun/VLCTube#87]
i used a quote from your script :p 

to the point, sometimes when i play a video, the video begins to play in the background somehow.
this only started when i updated to firefox 47.0.1 (32bit) stable release.
im gonna check with my copy of the nightly version to see if the same issue happens.

**Comment by Sonic0170** [comment]
scratch that last part, VLCTube no longer works in the nightly version of firefox which my current version is, 59.0a1 10/21/2016, no go on that test

**Comment by Sonic0170** [comment]
did a quick test on several older versions of VLCTube and i can say for sure that it wasn't something you changed, so either firefox changed something again or google/youtube has drastically changed their code again

**Comment by Sonic0170** [comment]
i will not that although VLCTube did load in a un-usuable state in my copy of firefox nightly, the video did still play in the background so im started to now suspect youtube changed again

**Comment by jackun** [comment]
Overriden document.createElement gets re-overriden by native code, or something. Made the video element load an empty source though firefox complains about invalid source.

**Comment by Sonic0170** [comment]
i found something strange after i stopped using VLCTube temporarily, sometimes when i open a video it loads the player, immediately starts playing the video and i have no controls at all.
im wondering if the way firefox handles html5 has gone haywire.
im guessing this error not related to vlctube in any way could be the culprit, i guess when i have time i should track down the reason why the player loads in a wrong way.
this broken loading of the player might explain why it happens, its very strange.

**Comment by Sonic0170** [comment]
went ahead and tried your fix and it didn't work because im thinking this error is out of your control, its also possibly my fault alone and maybe noone else is having this issue, time will tell

**Comment by Sonic0170** [comment]
idk why i didn't think to disable adblock plus on youtube, but now everything is working normal.
so far adblock plus seems to be at fault, ill update you if this problem reappears for whatever reason.
